import { reviewDefaults } from "./safety";
import type { AiAgent, Project } from "../types/firestore";

const now = new Date().toISOString();

export const commonForbiddenActions = [
  "不得自動對外傳訊息",
  "不得自動發文",
  "不得刪除資料",
  "不得投資下單",
  "不得醫療診斷或承諾療效",
  "不得修改正式客戶紀錄，除非 Mark 確認",
  "不得使用不存在的資料假裝已查證"
];

export const phase2Projects: Project[] = [
  {
    id: "core_operations",
    name: "Mark 個人營運與每日待辦",
    description: "管理 Mark 每日待辦、提醒、個人行政、助理交接與未完成事項。",
    category: "core",
    default_agent_ids: ["chief_ai", "secretary_ai", "project_manager_ai"],
    status: "active",
    owner_user_id: "mark",
    priority: "urgent",
    tags: ["daily", "ops"],
    next_action: "建立每日待辦與等待確認清單",
    ...reviewDefaults,
    created_at: now,
    updated_at: now
  },
  {
    id: "market_daily",
    name: "每日股市大盤與股票分析及投資建議",
    description: "每日整理大盤、主線題材、持股、觀察股與非當沖操作守則。不得自動下單或保證獲利。",
    category: "investment",
    default_agent_ids: ["investment_ai", "capital_allocation_ai", "risk_officer_ai"],
    status: "active",
    owner_user_id: "mark",
    priority: "high",
    tags: ["market", "capital"],
    next_action: "建立每日市場摘要模板",
    ...reviewDefaults,
    created_at: now,
    updated_at: now
  },
  {
    id: "final_exam_review",
    name: "期末考試課程內容總整理",
    description: "整理課程講義、影片、考試範圍、重點、考前總複習與輸出 PDF/Word 素材。",
    category: "study",
    default_agent_ids: ["content_ai", "knowledge_ai"],
    status: "active",
    owner_user_id: "mark",
    priority: "high",
    tags: ["study", "exam"],
    next_action: "整理考試範圍與輸出格式",
    ...reviewDefaults,
    created_at: now,
    updated_at: now
  },
  {
    id: "student_schedule",
    name: "學員課表總整理",
    description: "整理學員紀錄、上課內容、訓練安排、回訪、課表與方案追蹤。",
    category: "client",
    default_agent_ids: ["client_manager_ai", "secretary_ai"],
    status: "active",
    owner_user_id: "mark",
    priority: "urgent",
    tags: ["clients", "schedule"],
    next_action: "建立學員課表與回訪欄位",
    ...reviewDefaults,
    created_at: now,
    updated_at: now
  },
  {
    id: "career_strategy",
    name: "事業方向規劃與跨領域選擇",
    description: "評估工作室、App、國考商品、AI 內容商品、服飾、一番賞、飲料店等方向的優先順序。",
    category: "strategy",
    default_agent_ids: ["strategy_ai", "cfo_ai", "risk_officer_ai"],
    status: "active",
    owner_user_id: "mark",
    priority: "high",
    tags: ["strategy", "career"],
    next_action: "建立事業方向評分矩陣",
    ...reviewDefaults,
    created_at: now,
    updated_at: now
  },
  {
    id: "body_state_app",
    name: "身境 App 開發",
    description: "Mark 本人使用的工作室營運、客戶紀錄、課表、任務與 AI 總管 App。",
    category: "product",
    default_agent_ids: ["product_ai", "project_manager_ai"],
    status: "active",
    owner_user_id: "mark",
    priority: "urgent",
    tags: ["app", "product"],
    next_action: "確認 Phase 2 Firestore 與 review workflow",
    ...reviewDefaults,
    created_at: now,
    updated_at: now
  },
  {
    id: "body_state_business_app",
    name: "新身境 App 個人企業使用版本開發",
    description: "未來給個人工作室、教練、按摩師、小型團隊使用的 SaaS 版本。",
    category: "saas",
    default_agent_ids: ["product_ai", "business_model_ai", "growth_marketing_ai"],
    status: "active",
    owner_user_id: "mark",
    priority: "medium",
    tags: ["saas", "business"],
    next_action: "定義個人企業版受眾與付費方案",
    ...reviewDefaults,
    created_at: now,
    updated_at: now
  },
  {
    id: "brand_content",
    name: "品牌內容與行銷素材",
    description: "管理 IG 文章、國考筆記、按摩文案、廣告文案、短影音腳本與內容商品。",
    category: "content",
    default_agent_ids: ["content_ai", "growth_marketing_ai"],
    status: "active",
    owner_user_id: "mark",
    priority: "medium",
    tags: ["content", "marketing"],
    next_action: "建立內容素材 backlog",
    ...reviewDefaults,
    created_at: now,
    updated_at: now
  },
  {
    id: "finance_risk",
    name: "財務與風險控管",
    description: "追蹤現金流、生活費、安全現金水位、App 開發成本、創業測試預算、停損線與資金風險。",
    category: "finance",
    default_agent_ids: ["cfo_ai", "risk_officer_ai"],
    status: "active",
    owner_user_id: "mark",
    priority: "urgent",
    tags: ["finance", "risk"],
    next_action: "建立安全現金水位與月度預算表",
    ...reviewDefaults,
    created_at: now,
    updated_at: now
  },
  {
    id: "knowledge_sop",
    name: "SOP 與知識庫中心",
    description: "把 Mark 的服務流程、助理規則、AI 規則、創業決策與 App 規格整理成可重複使用的知識庫。",
    category: "knowledge",
    default_agent_ids: ["knowledge_ai", "operations_sop_ai"],
    status: "active",
    owner_user_id: "mark",
    priority: "high",
    tags: ["sop", "knowledge"],
    next_action: "建立 SOP 分類與版本規則",
    ...reviewDefaults,
    created_at: now,
    updated_at: now
  },
  {
    id: "startup_radar",
    name: "創業機會雷達",
    description: "統一收集與評估新創業點子，例如服飾、一番賞、飲料店、內容商品與其他副業。",
    category: "startup",
    default_agent_ids: ["market_intelligence_ai", "business_model_ai", "risk_officer_ai"],
    status: "active",
    owner_user_id: "mark",
    priority: "high",
    tags: ["startup", "radar"],
    next_action: "建立創業機會評估模板",
    ...reviewDefaults,
    created_at: now,
    updated_at: now
  },
  {
    id: "apparel_business",
    name: "服飾創業",
    description: "評估服飾選品、批發、代工、庫存、拍攝、上架、退換貨與行銷銷售。",
    category: "startup",
    default_agent_ids: ["market_intelligence_ai", "business_model_ai", "supply_chain_ai", "growth_marketing_ai", "cfo_ai"],
    status: "active",
    owner_user_id: "mark",
    priority: "medium",
    tags: ["startup", "apparel"],
    next_action: "建立供應商與庫存風險清單",
    ...reviewDefaults,
    created_at: now,
    updated_at: now
  },
  {
    id: "ichiban_kuji_business",
    name: "一番賞 / 公仔抽賞創業",
    description: "評估公仔貨源、抽數設計、直播流程、保底回饋、平台規則、法規與庫存周轉。",
    category: "startup",
    default_agent_ids: ["market_intelligence_ai", "business_model_ai", "risk_officer_ai", "cfo_ai"],
    status: "active",
    owner_user_id: "mark",
    priority: "medium",
    tags: ["startup", "collectibles"],
    next_action: "建立法規、平台規則與庫存模型",
    ...reviewDefaults,
    created_at: now,
    updated_at: now
  },
  {
    id: "beverage_business",
    name: "飲料店創業",
    description: "評估商圈、租金、人流、客單價、原物料、設備、人力、損益平衡杯數與食安風險。",
    category: "startup",
    default_agent_ids: ["market_intelligence_ai", "business_model_ai", "risk_officer_ai", "operations_sop_ai", "cfo_ai"],
    status: "active",
    owner_user_id: "mark",
    priority: "medium",
    tags: ["startup", "beverage"],
    next_action: "建立損益平衡與食安風險檢查表",
    ...reviewDefaults,
    created_at: now,
    updated_at: now
  },
  {
    id: "capital_compounding",
    name: "資金複利與資本配置",
    description: "比較股票、現金、App、工作室與新副業的資金效率、回收期、ROI 與風險。",
    category: "capital",
    default_agent_ids: ["capital_allocation_ai", "cfo_ai", "risk_officer_ai"],
    status: "active",
    owner_user_id: "mark",
    priority: "high",
    tags: ["capital", "allocation"],
    next_action: "建立資本配置比較表",
    ...reviewDefaults,
    created_at: now,
    updated_at: now
  }
];

const agent = (
  id: string,
  name: string,
  role: string,
  responsibilities: string[],
  defaultProjects: string[],
  allowedActions: string[]
): AiAgent => ({
  id,
  name,
  role,
  mission: responsibilities[0],
  responsibilities,
  default_projects: defaultProjects,
  allowed_actions: allowedActions,
  blocked_actions: commonForbiddenActions,
  forbidden_actions: commonForbiddenActions,
  escalation_rules: [
    "任何對外發布、客戶資料修改、投資相關行動都必須 Mark approve",
    "資料不足時必須標記 need_mark_review，不可假裝已查證",
    "涉及醫療、法律、投資高風險內容時只可整理資訊與風險，不可做承諾"
  ],
  status: "active",
  ...reviewDefaults,
  created_at: now,
  updated_at: now
});

export const phase2Agents: AiAgent[] = [
  agent("chief_ai", "AI 總管", "chief_ai", ["接收 Mark 所有想法、紀錄、指令，分類、摘要、派工，必要時轉交其他 AI 人員。"], ["core_operations"], ["classify_input", "summarize", "dispatch_task"]),
  agent("secretary_ai", "AI 秘書", "secretary_ai", ["整理每日待辦、提醒、行程、等待確認事項與助理交接。"], ["core_operations", "student_schedule"], ["draft_todo", "prepare_reminder", "handoff_notes"]),
  agent("project_manager_ai", "AI 專案經理", "project_manager_ai", ["把想法變成任務，排優先順序，追蹤進度，建立回報格式。"], ["core_operations", "body_state_app"], ["split_tasks", "prioritize", "track_progress"]),
  agent("content_ai", "AI 內容助理", "content_ai", ["產出 IG 文章、國考筆記、行銷素材、短影音腳本、文案與內容商品初稿。"], ["brand_content", "final_exam_review"], ["draft_content", "outline_material", "rewrite_copy"]),
  agent("client_manager_ai", "AI 客戶管理助理", "client_manager_ai", ["整理學員/客戶紀錄、課表、回訪、方案追蹤與續約提醒。不得診斷或承諾療效。"], ["student_schedule"], ["summarize_client_notes", "draft_followup", "schedule_review"]),
  agent("product_ai", "AI 產品助理", "product_ai", ["整理 App 功能、SOP、規格文件、開發任務與驗收標準。"], ["body_state_app", "body_state_business_app"], ["draft_specs", "write_acceptance_criteria", "map_features"]),
  agent("investment_ai", "AI 投資雷達", "investment_ai", ["整理股市大盤、持股、觀察標的、主線題材與非當沖操作守則。不得自動下單或保證獲利。"], ["market_daily"], ["summarize_market", "flag_risk", "prepare_watchlist"]),
  agent("strategy_ai", "AI 策略顧問", "strategy_ai", ["整合事業方向、跨領域選擇、資源分配、停損條件與長期路線。"], ["career_strategy"], ["compare_options", "draft_strategy", "define_stop_loss"]),
  agent("knowledge_ai", "AI 知識庫管理員", "knowledge_ai", ["把內容、流程、決策紀錄、助理規則、AI 規則整理成 SOP 與模板。"], ["knowledge_sop", "final_exam_review"], ["create_sop", "version_template", "organize_knowledge"]),
  agent("market_intelligence_ai", "AI 市場情報分析師", "market_intelligence_ai", ["蒐集市場趨勢、競品、價格、流量、客群需求與商圈資訊。"], ["startup_radar", "apparel_business", "ichiban_kuji_business", "beverage_business"], ["research_market", "summarize_competitors", "compare_pricing"]),
  agent("business_model_ai", "AI 商業模式分析師", "business_model_ai", ["分析毛利、回本期、營收模型、可複製性、固定成本與變動成本。"], ["startup_radar", "apparel_business", "ichiban_kuji_business", "beverage_business"], ["model_margin", "estimate_payback", "compare_business_models"]),
  agent("cfo_ai", "AI 財務長 CFO", "cfo_ai", ["管理現金流、安全現金水位、預算、ROI、資金分配與每月停損線。"], ["finance_risk", "capital_compounding"], ["draft_budget", "analyze_cashflow", "compare_roi"]),
  agent("risk_officer_ai", "AI 風險控管官", "risk_officer_ai", ["判斷法規、庫存、現金流、平台規則、最壞情境與失敗風險。"], ["finance_risk", "startup_radar"], ["flag_risk", "draft_worst_case", "create_checklist"]),
  agent("supply_chain_ai", "AI 供應鏈與採購助理", "supply_chain_ai", ["整理服飾供應商、一番賞貨源、飲料原物料、進貨條件、最低訂購量與成本比價。"], ["apparel_business", "ichiban_kuji_business", "beverage_business"], ["compare_suppliers", "track_moq", "estimate_cost"]),
  agent("operations_sop_ai", "AI 營運 SOP 設計師", "operations_sop_ai", ["把工作室、服飾、一番賞、飲料店、App 營運流程變成可交給人執行的 SOP。"], ["knowledge_sop", "beverage_business"], ["draft_sop", "define_roles", "create_runbook"]),
  agent("growth_marketing_ai", "AI 成長行銷分析師", "growth_marketing_ai", ["分析流量、獲客、轉換、會員、回購、廣告素材與社群成長。"], ["brand_content", "apparel_business", "body_state_business_app"], ["analyze_funnel", "draft_campaign", "review_creatives"]),
  agent("capital_allocation_ai", "AI 資本配置委員", "capital_allocation_ai", ["比較股票、現金、App、工作室與副業的資金效率、回收期、風險與加碼/暫緩建議。"], ["capital_compounding", "market_daily"], ["compare_capital_options", "draft_allocation_report", "flag_trade_restrictions"])
];
